services:
  task-worker:
    restart: unless-stopped
    build:
      context: .
      dockerfile: apps/task-worker/Dockerfile
    env_file:
      - .env
    command: [ "pnpm", "--filter", "@semantask/task-worker", "start" ]
